default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: killboard_development

test:
  <<: *default
  database: killboard_test

production:
  <<: *default
  database: killboard_production
  username: killboard
  password: <%= ENV['KILLBOARD_DATABASE_PASSWORD'] %>
